// Layer D — the five abilities, as pure board transforms (gameplay.md §13).
//
// Nothing here resolves a turn. Each function takes the board and returns the
// board the ACTION phase hands to SETTLE, so an ability is exactly as much of
// the turn as a move is: the thing that happens before gravity. That is AC-1406
// made structural — an ability cannot be "as well as" a move, because there is
// only one ACTION phase and this is what it does.
//
// SCOPE SCALES WITH SIZE, and it is the design's whole claim (§13.1): rat acts
// on one animal, fox on one turn's actions, elk on one species, elephant on the
// board's layout, buffalo on THE ONE OBJECT THE RULES MAKE PERMANENT. That last
// rung used to read "time itself", which was Hold the Line's freeze; Hold is
// withdrawn (§13.2g) and Stand Down took its slot, so the rung now reads as the
// exception to every other rule in the game. `scope` below is an ORDINAL, not a
// label, so the claim is a number a test can read rather than a sentence in a
// comment — test/abilities.test.js asserts it equals the species' own size.

import { BOARD, BUFFALO, DRAWABLE, SPECIES } from './constants.js';

/** Fox's Dart: how many moves the turn is worth instead of one (AC-1407). */
export const DART_MOVES = 3;

/**
 * Buffalo's Stand Down: how many broken segments fill the meter (AC-1433).
 *
 * THE SECOND CURRENCY, and it is not a discount on the first. Charges are
 * earned by score and score is earned by clearing rows, and the late game is
 * the phase in which the player stops clearing rows — measured, score per turn
 * falls 33% from the middle of a run to its last fifteen turns while the herd's
 * locked load doubles (§13.2f-ii). So a charge-priced anti-buffalo tool is at
 * its dearest, in real terms, at the exact moment it is for; measured against a
 * full roster a 3-charge one is taken 0.01 times a run (AC-1405L).
 *
 * The meter fills from the one event that is MORE frequent late — a buffalo
 * segment broken by a completed row, +48% per turn in the second half of a run.
 * The currency is generated by the problem it solves, which is the whole
 * argument for it being a currency rather than a price (AC-1433c).
 *
 * TEN, measured (AC-1434): 0.98 uses a run, +11% median, +97% p90, and only +3%
 * on run length — so it buys score rather than time. The levers are named in
 * advance: too dear -> 9, too generous -> 12. Do not reach for a charge price.
 *
 * It is in TUNING_SURFACE (src/ui/session.js), so moving it discards every
 * stored resume — which it must, since the same moves would otherwise replay
 * into a meter that was full on a different turn.
 */
export const STAND_DOWN_SEGMENTS = 10;

/**
 * The five. One per species, keyed by the ability rather than by the species,
 * because the player chooses an ability and the species is the flavour.
 *
 * `target` says what the caller must supply: an animal id, a species, or
 * nothing. `scope` is the ordinal described above.
 *
 * `cost` is AC-1405h, and it is a CONSTANT PER ABILITY and not a function of
 * `scope` — deliberately, and the temptation to derive it is the thing to
 * resist. Scope follows size; price follows measured value (§13.2d), and the
 * two ladders do not agree: Stand Down has the largest scope in the set and
 * costs NO charge at all, because it is bought in the second currency
 * (`meter`). Deriving cost from size would charge the most for it.
 *
 * Two fields carry behaviour as DATA rather than only as code, and both are
 * load-bearing for the fingerprint (AC-1430b):
 *
 *   `packs`  Burrow left-packs the row it emptied (AC-1428). Burrow's COST did
 *            not move in this pass, so without this field the one change that
 *            alters a board without altering a constant would be invisible to
 *            `TUNING_SURFACE` — and a behaviour change the surface cannot see
 *            is the one shape of AC-1016's bug the surface cannot catch.
 *   `meter`  Stand Down is bought with STAND_DOWN_SEGMENTS broken segments
 *            rather than with charges (AC-1433), so "what does this cost" is
 *            answered by the ability's own data and not by a branch on its id.
 *
 * These are in `TUNING_SURFACE` (src/ui/session.js) by virtue of being fields
 * of this object, so a reprice discards every resume written before it — which
 * it must, because the same moves would otherwise replay into a different
 * charge count.
 */
export const ABILITIES = Object.freeze({
  burrow: Object.freeze({
    id: 'burrow', species: 'rat', scope: 1, cost: 1, target: 'animal', packs: true,
  }),
  dart: Object.freeze({
    id: 'dart', species: 'fox', scope: 2, cost: 1, target: null,
  }),
  migrate: Object.freeze({
    id: 'migrate', species: 'elk', scope: 3, cost: 2, target: 'species',
  }),
  stampede: Object.freeze({
    id: 'stampede', species: 'elephant', scope: 4, cost: 2, target: null,
  }),
  standDown: Object.freeze({
    id: 'standDown', species: 'buffalo', scope: 5, cost: 0, target: null, meter: true,
  }),
});

/**
 * What this ability costs in charges (AC-1405h). One lookup, no arithmetic.
 *
 * IT HAS NO DEFAULT, and AC-1430 is why. It used to answer 0 for an id it did
 * not know, which is "free" — so a stored `{t:'A', ability:'hold'}` surviving
 * into the reducer would have been granted for nothing rather than refused.
 * Nothing reaches this with an unknown id today (`parseResume` rejects the move
 * and `abilityFault` rejects the action, both before this line), and the point
 * is that if anything ever does it must be LOUD rather than free.
 *
 * Own-property, for AC-1022's `__proto__` reason: `ABILITIES['__proto__']` is
 * truthy and is not an ability.
 */
export function abilityCost(ability) {
  if (!Object.prototype.hasOwnProperty.call(ABILITIES, ability)) {
    throw new Error(`no such ability: ${String(ability)}`);
  }
  return ABILITIES[ability].cost;
}

/** In scope order, which is species-size order. The sheet renders this list. */
export const ABILITY_IDS = Object.freeze(
  Object.keys(ABILITIES).sort((a, b) => ABILITIES[a].scope - ABILITIES[b].scope),
);

/**
 * AC-1412: buffalo is not a selectable Migrate target.
 *
 * Derived from DRAWABLE rather than written out, so a species added to the game
 * becomes migratable without anyone remembering to come back here — and buffalo
 * stays out because buffalo is the one species that is never drawn.
 */
export const MIGRATE_SPECIES = DRAWABLE;

/**
 * Left-pack rows: within each row, animals keep their left-to-right order and
 * are pushed against the wall in that order.
 *
 * ONE PACKING ALGORITHM, two abilities. Stampede packs every row (AC-1411) and
 * Burrow packs the single row it emptied (AC-1428) — "Stampede's effect at the
 * smallest possible scope" is the design's own wording, so it should be the same
 * function at a different scope rather than a second implementation of the same
 * arithmetic. AC-1428b then falls out for free: the row holds exactly the cells
 * it held before, so packing can never COMPLETE a row, at either scope. A row
 * that was two cells short is two cells short afterwards.
 *
 * `rows` is a Set of rows to pack, or null for every row.
 *
 * Gravity is NOT applied here. The caller's SETTLE phase does it, the same way
 * it does for a move — which is what keeps one gravity in the engine.
 */
export function packRows(animals, rows = null) {
  const byRow = new Map();
  for (const animal of animals) {
    if (rows && !rows.has(animal.y)) continue;
    if (!byRow.has(animal.y)) byRow.set(animal.y, []);
    byRow.get(animal.y).push(animal);
  }
  const moved = [];
  const next = new Map();
  for (const [, row] of byRow) {
    // Sort by x. Two animals in one row cannot share an x, so this is total.
    const ordered = row.slice().sort((a, b) => a.x - b.x);
    let cursor = 0;
    for (const animal of ordered) {
      if (animal.x !== cursor) {
        // `y` rides along because the presentation staggers the slide from the
        // bottom row up (ui.md §13.4) and would otherwise have to look every
        // animal back up on a board the engine has already changed.
        moved.push({ id: animal.id, y: animal.y, fromX: animal.x, toX: cursor });
      }
      next.set(animal.id, cursor);
      cursor += animal.size;
    }
  }
  // Rebuild in the INPUT order, never in row order: `animals` order is part of
  // the engine's determinism (applyGravity's sort is stable) and re-ordering it
  // here would make the board depend on how this function happened to iterate.
  //
  // `next` only holds the packed rows, so an animal outside them is returned
  // untouched — which is what makes the one-row scope safe.
  return {
    animals: animals.map((a) => (
      next.has(a.id) && next.get(a.id) !== a.x ? { ...a, x: next.get(a.id) } : a
    )),
    moved,
  };
}

/** Elephant's Stampede: left-pack EVERY row (AC-1411). */
export function stampede(animals) {
  return packRows(animals);
}

/**
 * Buffalo's Stand Down: every buffalo loses all but one segment (AC-1419).
 *
 * `size` becomes 1, `x` unchanged, and NOTHING IS REMOVED — which is the whole
 * of AC-1418. AC-1412b forbids an ability REMOVING a buffalo, on two grounds
 * that are both objections to a cheap removal; this changes the one field the
 * rules already change, by the one mechanism they already use, and leaves the
 * buffalo on the board still refusing to clear and still owing its row. The
 * commitment goes from five completions to one; it is not skipped.
 *
 * A buffalo already at size 1 is untouched and is NOT a reason to refuse the
 * ability (AC-1422): the chips show one bar each, so the player has been told
 * exactly what they are buying, and the engine does not second-guess a legal
 * purchase.
 *
 * It scores NOTHING (AC-1420), and that is enforced by where the shrink is
 * reported rather than by a rule: the +50 a segment is paid by
 * `resolveClears`' CLEAR_STEP events, and these shrinks are carried on the
 * ACTION event instead. A button is not a completed row. The same fact keeps
 * `stats.buffaloShrinks` — and therefore the meter itself — untouched by this,
 * so the ability cannot refill its own currency.
 */
export function standDown(animals) {
  const shrunk = [];
  const next = animals.map((animal) => {
    if (animal.type !== BUFFALO || animal.size <= 1) return animal;
    shrunk.push({ id: animal.id, fromSize: animal.size, toSize: 1 });
    return { ...animal, size: 1 };
  });
  return { animals: next, shrunk };
}

/**
 * Rat's Burrow: one animal of the player's choice leaves, AND THE ROW IT WAS
 * STANDING IN CLOSES UP (AC-1428).
 *
 * The left-pack is the second lever §13.2e named in advance and then applied:
 * the revisit condition was met twice, by two measurements on two curves, and
 * the reprice to 1 charge did not fix it. With the pack it is +26% median at
 * the lowest price in the set — the highest median delta there is.
 *
 * THREE THINGS IT DELIBERATELY IS NOT. Not a second Stampede: one row, the row
 * the removed animal was standing in, and a player who wants a different row
 * spends a different charge. Not a row-completer (AC-1428b): packing is a
 * permutation of that row's occupancy, so the REMOVAL is still the only thing
 * that changes it, by exactly one animal. Not a buffalo tool (AC-1428c): the
 * packed row may contain a buffalo and that buffalo packs like any other body —
 * its `x` may move, its `size` may not.
 */
export function burrow(animals, id) {
  const victim = animals.find((a) => a.id === id);
  const left = animals.filter((a) => a.id !== id);
  if (!victim) return { animals: left, removedIds: [], moved: [] };
  const packed = packRows(left, new Set([victim.y]));
  return { animals: packed.animals, removedIds: [victim.id], moved: packed.moved };
}

/** Elk's Migrate: every animal of one species leaves (AC-1412). */
export function migrate(animals, type) {
  return {
    animals: animals.filter((a) => a.type !== type),
    removedIds: animals.filter((a) => a.type === type).map((a) => a.id),
  };
}

export const ABILITY_UNKNOWN = 'unknown-ability';
export const ABILITY_NO_CHARGE = 'no-charge';
export const ABILITY_DISABLED = 'abilities-disabled';
export const ABILITY_BAD_TARGET = 'bad-target';
export const ABILITY_DART_ACTIVE = 'dart-active';
/** AC-1433: the meter is short. The second currency's ABILITY_NO_CHARGE. */
export const ABILITY_METER_LOW = 'meter-low';
/** AC-1421: a full meter and nothing to spend it on. The meter is NOT emptied. */
export const ABILITY_NO_BUFFALO = 'no-buffalo';

/**
 * Why this ability may not be used right now, or null.
 *
 * Returning a REASON rather than a boolean is what lets the sheet say why a row
 * is unaffordable instead of implying it (ui.md §13.2), and it means the engine
 * and the sheet cannot disagree about affordability — there is one predicate.
 *
 * A target that is not on the board is a fault rather than a legal waste: a
 * charge that evaporates for nothing is the opposite of an assist. AC-1402 is
 * untouched by that — it is about the ABILITY's own species (Burrow works with
 * no rat on the board), not about the target the player picks.
 */
export function abilityFault(state, ability, target) {
  if (!Object.prototype.hasOwnProperty.call(ABILITIES, ability)) return ABILITY_UNKNOWN;
  if (!state.abilities) return ABILITY_DISABLED;
  if (state.dart > 0) return ABILITY_DART_ACTIVE;
  // AC-1405h: the price is per ability, so "can I afford this" is now a real
  // question at the sheet rather than one answer for all five rows.
  if (state.charges < ABILITIES[ability].cost) return ABILITY_NO_CHARGE;
  const spec = ABILITIES[ability];
  // AC-1433: the second currency, asked the same question in its own unit. The
  // charge test above passes trivially for it — `cost` is 0 — so this is not an
  // exception to the price check, it IS the price check for the one ability
  // whose price is not in charges.
  if (spec.meter) {
    if (state.standDownMeter < STAND_DOWN_SEGMENTS) return ABILITY_METER_LOW;
    // AC-1421. The first no-target ability that can have nothing to do, so the
    // rule is stated rather than inherited: it is a FAULT, which means the use
    // is rejected before `reduce` reaches the meter, so the meter still holds.
    // A full meter that evaporates for nothing is the opposite of an assist.
    if (!state.animals.some((a) => a.type === BUFFALO)) return ABILITY_NO_BUFFALO;
  }
  if (spec.target === 'animal') {
    const animal = state.animals.find((a) => a.id === target);
    // AC-1412b: the buffalo is not removable by any ability, Burrow included.
    if (!animal || !isAbilityRemovable(animal.type)) return ABILITY_BAD_TARGET;
  }
  if (spec.target === 'species') {
    if (!MIGRATE_SPECIES.includes(target)) return ABILITY_BAD_TARGET;
    if (!state.animals.some((a) => a.type === target)) return ABILITY_BAD_TARGET;
  }
  return null;
}

/**
 * Apply an ability's board effect. Returns the ACTION event the turn records,
 * plus the board SETTLE is about to run gravity on.
 *
 * Dart alone touches no animal: its effect is on the turn, and it lives in the
 * reducer where turns are. Nothing here suppresses an arrival, because nothing
 * in the game does any more (AC-1410, AC-1427).
 *
 * `shrunk` is Stand Down's and only Stand Down's, and it rides the ACTION event
 * rather than a CLEAR_STEP for AC-1420's reason: CLEAR_STEP is what pays +50 a
 * segment and what `stats.buffaloShrinks` — the meter's own unit — is folded
 * from. Reporting it here is what makes "it scores nothing and it does not
 * refill its own meter" structural rather than remembered.
 */
export function applyAbility(animals, ability, target) {
  switch (ability) {
    case ABILITIES.burrow.id: {
      const out = burrow(animals, target);
      return {
        animals: out.animals, removedIds: out.removedIds, moved: out.moved, shrunk: [],
      };
    }
    case ABILITIES.migrate.id: {
      const out = migrate(animals, target);
      return { animals: out.animals, removedIds: out.removedIds, moved: [], shrunk: [] };
    }
    case ABILITIES.stampede.id: {
      const out = stampede(animals);
      return { animals: out.animals, removedIds: [], moved: out.moved, shrunk: [] };
    }
    case ABILITIES.standDown.id: {
      const out = standDown(animals);
      return { animals: out.animals, removedIds: [], moved: [], shrunk: out.shrunk };
    }
    default:
      return { animals, removedIds: [], moved: [], shrunk: [] };
  }
}

/**
 * Is any animal standing in the danger band? AC-1408b's "row 11 or above".
 *
 * THE ONLY DEFINITION, and it lives in the engine because Layer D made it a
 * RULE as well as a rendering: it decides when Last Stand fires, and it decides
 * when the board's pulse lights. Those two must be the same instant — ui.md
 * §13.4 asks for the warning and the help to read as one event — and two
 * functions that agree are the §6.3 bug shape rather than its absence. The UI
 * imports this one (src/ui/components/Board.js); a hygiene test refuses a
 * second copy.
 *
 * Row 14 is inside "or above" and is never seen: occupying it ends the run in
 * the same JUDGE phase, and no charge is granted on a turn that ends the run.
 */
export function inDangerBand(animals) {
  return animals.some((a) => a.y >= BOARD.dangerBandLow);
}

/**
 * The species each ability belongs to, as the tray and the sheet draw it.
 * Exported so the UI never re-derives the pairing from a second table.
 */
export function abilitySpecies(ability) {
  return SPECIES[ABILITIES[ability].species];
}

/** Buffalo is never a Migrate target, and this is the executable form of it. */
export function isMigratable(type) {
  return isAbilityRemovable(type) && MIGRATE_SPECIES.includes(type);
}

/**
 * AC-1412b — no ability removes the buffalo, and the rule is per-OBJECT.
 *
 * AC-1412 wrote it as a property of Migrate, so Burrow shipped able to delete
 * a size-5 buffalo for one rat charge — five clears' worth of work, and the
 * obstacle the whole of §6.4 is built around. The buffalo is a different KIND
 * of thing: it refuses to clear, it shrinks rather than leaving, and nothing
 * in the game removes it in one move. This is that, stated once, for every
 * ability that removes anything.
 */
export function isAbilityRemovable(type) {
  return type !== BUFFALO;
}
